In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix


In [3]:
dataset = pd.read_csv('default-of-credit-card-clients.csv', header=1)


In [4]:
Headers = list(dataset.columns.values)


In [5]:
X = dataset.iloc[:, 1:24].values
y = dataset.iloc[:, -1].values


In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
sc = StandardScaler()

In [8]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

C:\Users\sesha\AppData\Roaming\Python\Python37\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [9]:
print('Training Features Shape:', X_train.shape)
print('Training Labels Shape:', y_train.shape)
print('Testing Features Shape:', X_test.shape)
print('Testing Labels Shape:', y_test.shape)

Training Features Shape: (24000, 23)
Training Labels Shape: (24000,)
Testing Features Shape: (6000, 23)
Testing Labels Shape: (6000,)


In [10]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 1000, random_state = 42)
rf.fit(X_train, y_train);

In [10]:
predictions = rf.predict(X_test)
print(predictions)

[0 0 0 ... 0 1 0]


In [11]:
#Random 100 predictions

for i in range(0,10):
    print("Actual outcome :: {} and Predicted outcome :: {}".format(list(y_test)[i], predictions[i]))

   


Actual outcome :: 0 and Predicted outcome :: 0
Actual outcome :: 0 and Predicted outcome :: 0
Actual outcome :: 0 and Predicted outcome :: 0
Actual outcome :: 0 and Predicted outcome :: 0
Actual outcome :: 0 and Predicted outcome :: 0
Actual outcome :: 1 and Predicted outcome :: 0
Actual outcome :: 1 and Predicted outcome :: 0
Actual outcome :: 0 and Predicted outcome :: 0
Actual outcome :: 0 and Predicted outcome :: 0
Actual outcome :: 0 and Predicted outcome :: 0


In [11]:
import _pickle as pk
filename = 'finalized_model.sav'
pk.dump(rf, open(filename, 'wb'))


In [16]:
model = pk.load(open(filename, 'rb'))


In [12]:
print(rf.score(X_train,y_train))

0.999625


In [13]:
y_pred = rf.predict(X_test)
print(y_pred)

from sklearn import metrics

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))  



[0 0 0 ... 0 1 0]
Mean Absolute Error: 0.17816666666666667
Mean Squared Error: 0.17816666666666667
Root Mean Squared Error: 0.42209793492348036


In [14]:
y_predict = rf.predict(X_test)
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_predict)
print(confusion_matrix)

[[4449  254]
 [ 815  482]]


In [24]:
def score():
    y = rf.score(X_train,y_train)
    l1.config(text=y)


In [25]:
def write(data):
    import csv 

    myFile = open('Output.csv', 'w')  
    with myFile:  
        writer = csv.writer(myFile)
        writer.writerow(data)


In [26]:
def read():
    import csv
 
    with open('Output.csv', newline='') as File:  
        reader = csv.reader(File)
        for row in reader:
            res = model.predict(row) 
            return res

In [27]:
def rfpredict():
    data = e.get()
    write(data)
    val = read()
    if val == 1:
        print("Yes")
    else:
        print("No")
        
    

In [28]:
from tkinter import *

root = Tk(className = "button_click_label")
root.geometry("400x400")

message = StringVar()
message.set('hi')

l1 = Label(root, text="hi")
e = Entry(root)
e.pack()


In [29]:
b1 = Button(root, text = " Random Forest Model Accuracy score", command = score).pack()
b2 = Button(root, text = "Random Forest Manual Prediction", command = rfpredict).pack()


In [30]:
l1 = Label(root, text="Click a button")


In [31]:
l1.pack()

In [ ]:
root.mainloop()


Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\program files\python37\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "<ipython-input-27-7db9f7a75548>", line 4, in rfpredict
    val = read()
  File "<ipython-input-26-f31917892897>", line 7, in read
    res = model.predict(row)
NameError: name 'model' is not defined


In [2]:
import csv
 
myData = 22,120000,2,2,1,39,-1,-1,-1,-1,-1,-1,316,316,316,0,632,316,316,316,0,632,316,0,1 

myFile = open('Output.csv', 'w')  
with myFile:  
    writer = csv.writer(myFile)
    writer.writerow(myData)


In [35]:
import csv
 
with open('Output.csv', newline='') as File:  
    reader = csv.reader(File)
    for row in reader:
          data = np.resize(data,(1, -1))
    print(rf.predict(data)) 

[0]


In [12]:
from sklearn.datasets.samples_generator import make_blobs


0.826333333333
